version: '3.4'

services:
  postgres_database:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
      - "./database/database_init.sql:/docker-entrypoint-initdb.d/create_tables.sql"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=customer
    restart: always
  pgadmin4:
    image: dpage/pgadmin4:latest
    ports:
      - "80:80"
    volumes:
      - "./data/pgadmin:/var/lib/pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    restart: always
    depends_on:
      - postgres_database
  customers:
    image: customers
    ports:
      - "5001:80"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_database