version: '3.8'

services:
  postgres_database:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=customer
    restart: always
  pgadmin4:
    image: dpage/pgadmin4:latest
    ports:
      - "80:80"
    volumes:
      - "./data/pgadmin:/var/lib/pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    restart: always